### ISSUE TITLE
Fail to install Treafik/Authelia

### ISSUE THREAD

**Issue by GamermadHD** [dockserver/dockserver#12]
When installing these issues appears at top above install text - 

error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).

Also when entering a password into the text it shows blank?

Once entering all details and try to deploy this is displayed - 
```sh
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    ❌ ERROR -> compose check has failed
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Confirm Info | PRESS [ENTER]

```

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/7714fd95e1608293153b1e1404501df299fe3ebd
