### ISSUE TITLE
Installation scripts adding wrong authelia policys

### ISSUE THREAD

**Issue by brtbach** [dockserver/dockserver#179]
When you install stuff which need bypass policys (e.g. tautulli, librespeed, plex) smth breaking the authelia config:

    - domain: authelia.mydomain.de
    - domain: tautulli.mydomain.de
      policy: bypass
	  policy: bypass
    - domain: plex.mydomain.de
      policy: bypass
	  policy: bypass
    - domain: librespeed.mydomain.de
      policy: bypass
	  policy: bypass

**Comment by doob187** [comment]
Can you post the completed file 

Redacted  DOMAIN  and username plz

**Comment by FSCorrupt** [comment]
had the problem with petio today, here is how it looks after install:
![image](https://user-images.githubusercontent.com/45659314/132123264-6381b6fa-b2f2-4c85-8b16-7c962672750e.png)

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/blob/master/traefik/templates/authelia/configuration.yml

Layout is different in Authelia

**Comment by doob187** [comment]
Will pushed to major update 


https://github.com/dockserver/dockserver/pull/203

**Comment by doob187** [comment]
This should fix it
