### ISSUE TITLE
Netdata issue

### ISSUE THREAD

**Issue by Wokjak69** [dockserver/dockserver#221]
Netdata container wont start

![image](https://user-images.githubusercontent.com/91158361/134240589-c7bd1f90-50dc-42fb-be2f-ae5e452b8899.png)

**Comment by DrAg0n141** [comment]
You are using the newest dockserver version? Its updated in the last update.

**Comment by Wokjak69** [comment]
> You are using the newest dockserver version? Its updated in the last update.

i'm using the latest version of DS

**Comment by Wokjak69** [comment]
> https://media.discordapp.net/attachments/835230901231026296/889973734625140776/unknown.png

forgot to upload the new error thank you doob

**Comment by DrAg0n141** [comment]
Pls Again Update Dockserver and Redeploy it :)

**Comment by Wokjak69** [comment]
> Pls Again Update Dockserver and Redeploy it :)

trying now <3

**Comment by Wokjak69** [comment]
its working now!!
