### ISSUE TITLE
Unable to run Conreq

### ISSUE THREAD

**Issue by FSCorrupt** [dockserver/dockserver#224]
Install works over DS Menu.
Couldn't connect to conreq.example.com, so i checked container log, got following error.

![Screenshot_20210922-175621__01](https://user-images.githubusercontent.com/45659314/134379521-9016f6ee-ad94-464b-8e5c-3e0e247b8fe0.jpg)

but Container is configurated with this Port:

PORT CONFIGURATION	
127.0.0.1:8071  8071/tcp

maybe something screwed up in yml?

**Comment by aelfa** [comment]
@FSCorrupt `sudo dockserver -u` & redeploy.

**Comment by FSCorrupt** [comment]
Solved, thanks for the fast fix!
