### ISSUE TITLE
Wholesale GPU

### ISSUE THREAD

**Issue by drag0n141** [dockserver/dockserver#225]
Add  /gpu test..
Add test if Hetzer or not 
Add test is Wholesale or not

intranetsnob followed the PTS Guide About that. https://github.com/MHA-Team/PTS-Team/wiki/Plex#5-configuring-hardware-encoding

**Comment by Ladrek69** [comment]
what is Wholesale GPU?

**Comment by justinglock40** [comment]
This should work automatically on Wholesale Internet, right? Or did they start using custom images?
