### ISSUE TITLE
Overseerr failed to start after fresh install

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#226]
**Describe the bug**
overseerr failed to stard 

**To Reproduce**
1. install from dockserver master branch

**Screenshots**

![image](https://user-images.githubusercontent.com/35934387/134559840-654d5c5d-76f5-4ea2-997f-3f082f38cc81.png)

**Comment by doob187** [comment]
Tried for 2 minutes 
No error

**Comment by doob187** [comment]
![Screenshot_20210923-204138_Chrome](https://user-images.githubusercontent.com/60312740/134565250-e769d4eb-13c4-4e17-8368-12e952901926.jpg)

**Comment by dan3805** [comment]
I do not know what is happening on my side, I even did the removal with dockserver and reinstall, it still does not work
