### ISSUE TITLE
FEATURE ADD : Remove CF DNS Entry on App Uninstall.

### ISSUE THREAD

**Issue by fscorrupt** [dockserver/dockserver#269]
It would be great if the CF DNS entries are removed when an app is uninstalled via the Dockserver menu. 

Script/Repo i found:

https://github.com/tech-otaku/cloudflare-dns

**Comment by doob187** [comment]
Its python used a lot of dependencies

**Comment by FSCorrupt** [comment]
found a Shell Script to:
https://github.com/jmcausing/Cloudflare-DNS-Manger-Linux-Script

**Comment by doob187** [comment]
Bump  before stale

**Comment by fscorrupt** [comment]
The following 2 lines can be used to remove a dns entry, the necessary variables are already contained in the **envmigrate.sh** .

First gets dnsrecord id from the app that gets removed, i already took the variable "$typed", i saw you use it in uninstall part of DS.

Second, removes the dnsrecord.

`dnsrecordid=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$DOMAIN1_ZONE_ID/dns_records?name=$typed.{$DOMAIN}" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $CLOUDFLARE_API_KEY" -H "Content-Type: application/json"  | grep -Po '(?<="id":")[^"]*' | head -1 )

result=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/$DOMAIN1_ZONE_ID/dns_records/$dnsrecordid" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $CLOUDFLARE_API_KEY" -H "Content-Type: application/json")`

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/pull/308
