### ISSUE TITLE
Uploader 'Syntax Error'

### ISSUE THREAD

**Issue by Intranetsnob** [dockserver/dockserver#272]
Uploader log upon redeployment: 

/app/tdrive/uploader.sh: line 68: [[: 100%: syntax error: operand expected (error token is "%")

**Comment by Intranetsnob** [comment]
Nevermind, team helped out, resulted in 100% disk space, had to manually clear some files for uploader to kick back up. Thanks.

**Comment by doob187** [comment]
Fix in lastest  push
