### ISSUE TITLE
Directories getting deleted

### ISSUE THREAD

**Issue by cyb3rgh05t** [dockserver/dockserver#287]
Since yesterday all folders in  /mnt/downloads are getting deleted.

The nzb or torrent folder is gone an i get in the arrs app that my remote path are not correct anymore.

Is there something that changed?

even in rutorrent all added torrents are added in pause mode and not in download mode
same for sabnzbd

**Comment by cyb3rgh05t** [comment]
i managed to fix this by downgrade uploder to ds384

**Comment by doob187** [comment]
Sorry for the delay

So I have fixed the bug for removing 

And I have a added a new logic  for backups to pick up better 

There is now no fixed folder for backups anymore 
It's will check the /mnt/downloads folder full automatic

**Comment by cyb3rgh05t** [comment]
no need to be sorry doob.

thanks for the fix

**Comment by cyb3rgh05t** [comment]
it is still removing/deleting the temp folder under downloads/torrents/ that causes that torrents arent downloading

**Comment by doob187** [comment]
Please pull again

**Comment by cyb3rgh05t** [comment]
seems to work now thanks doob for the fix

**Comment by cyb3rgh05t** [comment]
no soory it is still deleting the temp folder for torrents

**Comment by doob187** [comment]
Wo some test I have done with the folders 

This must be working now 
The folder will not removed anymore

**Comment by cyb3rgh05t** [comment]
so latest uploader is good?

**Comment by cyb3rgh05t** [comment]
using ghcr.io/dockserver/docker-uploader:dockserver-ds458 

it is still removing the temp folder if it is empty

**Comment by cyb3rgh05t** [comment]
i downgraded back again to ghcr.io/dockserver/docker-uploader:dockserver-ds384

latest uploader seems to still remove/delete Temp folder for torrents under /mnt/downloads/torrent if it is empty and for sabnzbd it deletes the categories folder like movies/movies4k/tv/tv4k under /mnt/downloads/nzb if these are empty.

**Comment by doob187** [comment]
I have removed the line

**Comment by cyb3rgh05t** [comment]
Thank you

**Comment by cyb3rgh05t** [comment]
seems to work now thanks doob
