### ISSUE TITLE
Service account emails not displayed GDSA unencrypted

### ISSUE THREAD

**Issue by clandorsdx** [dockserver/dockserver#30]
**Describe the Issue**
Service account emails not displayed after unencrypted Service Key Builder completes 

**To Reproduce**
1. Go to Google Service Key Builder
2. Select unencrypted 
3. Fill out info and deploy

**Expected behavior**
Once GDSA has completed emails that were created are listed to add to team drive

**Additional context**
Fixed on my machine by removing "1>/dev/null 2>&1" on line 234

**Comment by doob187** [comment]
Thx for Report 
@clandorsdx

**Comment by doob187** [comment]
@all-contributors please add @clandorsdx for bugs
