### ISSUE TITLE
Syntax error in uploader logs..

### ISSUE THREAD

**Issue by cyb3rgh05t** [dockserver/dockserver#300]
using uploader ds517

![image](https://user-images.githubusercontent.com/5200101/143032954-5d9b1265-b2e8-44ac-9b57-1f51d19638c1.png)

i get a syntax error in the logs

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/e851a0c41bffbcdcc53a4e5824b0eed4d74da49c
