### ISSUE TITLE
Uploader:  rclone.conf permission denied error 

### ISSUE THREAD

**Issue by ookla-ariel-ride** [dockserver/dockserver#335]
**Describe the bug**
uploader cannot find/use rclone.conf

**To Reproduce**
1. run the latest uploader container, check the log

here is the full error I get from the log:

today at 12:07:14 PM2022/01/03 20:07:14 Failed to load config file "/root/.rclone.conf": open /root/.rclone.conf: permission denied
today at 12:07:14 PM/app/uploader/uploader.sh: line 109: /1024**3 : syntax error: operand expected (error token is "/1024**3 ")
today at 12:07:14 PMMOVE FINISHED from /mnt/downloads to REMOTE
today at 12:07:14 PMCHECKING LOCAL SOURCE FOLDERS
today at 12:07:14 PMSTARTING RCLONE MOVE from /mnt/downloads to REMOTE
today at 12:07:21 PM2022/01/03 20:07:21 Failed to load config file "/root/.rclone.conf": open /root/.rclone.conf: permission denied
today at 12:07:21 PM/app/uploader/uploader.sh: line 109: /1024**3 : syntax error: operand expected (error token is "/1024**3 ")
today at 12:07:21 PMMOVE FINISHED from /mnt/downloads to REMOTE
today at 12:07:21 PMCHECKING LOCAL SOURCE FOLDERS
today at 12:07:22 PMSTARTING RCLONE MOVE from /mnt/downloads to REMOTE

**Comment by doob187** [comment]
https://github.com/doob187/container/tree/patch-1

**Comment by doob187** [comment]
A merge ca  be closed 

@doob187 
•
@drag0n141

**Comment by doob187** [comment]
# close
