### ISSUE TITLE
Uploader: Files being uploaded are added to a folder with the same name as the file being uploaded

### ISSUE THREAD

**Issue by ookla-ariel-ride** [dockserver/dockserver#337]
**Describe the bug**
Uploader is successfully uploading files, but it is placing these files in a folder that is the same name as the file. 

**To Reproduce**
1. Have radarr/sonarr successfully import new files
2. Have uploader upload these files
3. look at the destination of these uploads in /mnt/remotes (see attached image for more info)

**Expected behavior**
Uploaded files should go in the exact same folder structure that existed on the local filesystem

This issue is with the latest release of uploader

Here is a screenshot showing the behavior:
![Screenshot 2022-01-03 154330](https://user-images.githubusercontent.com/42082417/147992173-ef412a73-d7df-478f-902e-66a11390abb9.png)

**Comment by doob187** [comment]
https://github.com/dockserver/container/pull/52

**Comment by doob187** [comment]
# close
