### ISSUE TITLE
Theme changed on GilbN / theme.park

### ISSUE THREAD

**Issue by cyb3rgh05t** [dockserver/dockserver#343]
Hi devs,

little update:

**orgnaizr-dark**

 renamed to 

**organizr**

:)

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/blob/738765ce1f6ea9beb9cf4544d07ca07149084c8f/apps/.subactions/envmigrate.sh#L54

**Comment by drag0n141** [comment]
This is still changed at 1.11.2021 https://github.com/dockserver/dockserver/commit/5d6ca80f4cccffa00130dca5baed978ff22abc72#diff-e3b805bffff48e3a32831d4314f25316463b2b831172164633eb69fe93c3ef7b

**Comment by doob187** [comment]
!close

**Comment by cyb3rgh05t** [comment]
ok i see, i never updated it in my .env file for compose with dockserver -u.

sorry for that then.
