### ISSUE TITLE
Latest mount still not working

### ISSUE THREAD

**Issue by mrfret** [dockserver/dockserver#345]
Latest mount image gets error:
Error relocating /usr/bin/mergerfs: _ZSt28__throw_bad_array_new_lengthv: symbol not found

[Mount] -> rclone is running and working <-

mergerfs never starts it seems.

Rolling back to 3.15 works

**Comment by mrfret** [comment]
The files do show in remotes folder, but not unionfs. If this is what is supposed to happen, then it is working after all.

**Comment by doob187** [comment]
I worked on a new system workflow for the mount

This should take some time and I will test it a long time before It get Merged 

The fail of mergerfs is the libtarc++ is buggy on the alpine repositories 

So we can't fix them self the bug  is open in alpine self.

Till now no fix in the few days

**Comment by doob187** [comment]
Ther is just in option at the moment 

Roll back to ghcr.io/dockserver/docker-mount:v3.15-a0482dc2-ls1

It's used a older repository of alpine

**Comment by PlexPower** [comment]
Hi All. Same For me: ghcr.io/dockserver/docker-mount:v3.15-a0482dc2-ls1

But my friend do all installation maybe 2 weeks ago on mount:latest (v3.15.0-rc.4) still work. I told him do not update.

THX

**Comment by doob187** [comment]
Please  Wait  ( do not update ) 

the new wat don't needed anymore mergerfs
and less code lines 

You can follow  

https://github.com/dockserver/container/pull/53

To see what will come
