### ISSUE TITLE
Uploader: Weird folder and upload 1 by 1

### ISSUE THREAD

**Issue by RedBull01** [dockserver/dockserver#352]
Ubuntu 20.04

Hi all.

1: Sometime name_folder (2009) (1)

2: I think is your new version but upload 1 by 1

uploader.env:
```sh
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=1000
PGID=1000

## RCLONE - SETTINGS
BANDWITHLIMIT=null
LOG_LEVEL=INFO
DLFOLDER=/mnt/downloads
USERAGENT=XVK1H4wLW0UcyhqhjnXUo8MM5DgyqUI0

## USER - SETTINGS
DRIVEUSEDSPACE=null
MIN_AGE_FILE=10m
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
```
Thx again

**Comment by PlexPower** [comment]
Sorry… and

when i start Uploader. In Mount logs:

[Mount] -> rclone is running and working <-
[Mount] -> mergerfs is running and working <-
[Mount] -> rclone is running and working <-
[Mount] -> mergerfs is running and working <-
find: ‘/system/uploader/vfsforget’: No such file or directory
[Mount] -> rclone is running and working <-
[Mount] -> mergerfs is running and working <-

**Comment by doob187** [comment]
The upload just uploaded  one by  one 

There will be not editing to upload more as once


The (1) is a permissions issue not related  to the uploader self 


The vfsforget  is removed . Not needed anymore  in union rclone mount

**Comment by doob187** [comment]
IT will be fixed in the next release  of the mount ..

Before I need to test a long time .  . Before I/ wr merg them .
