### ISSUE TITLE
Uploader:  rclone.conf permission denied error with latest Uploader

### ISSUE THREAD

**Issue by ookla-ariel-ride** [dockserver/dockserver#354]
seeing this error with the latest Uploader container:

2022/01/22 17:02:29 Failed to load config file "/root/.rclone.conf": open /root/.rclone.conf: permission denied

**Comment by doob187** [comment]
https://github.com/dockserver/container/commit/ae3a304d7b16259615b56b7d871d9cd85ac792fb
