### ISSUE TITLE
LXC : mount docker not starting after reboot

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#357]
lately I noticed that after a LXC container reboot, I have to manually do the lxcstart.sh script

```sudo bash /opt/dockserver/preinstall/installer/subinstall/lxcstart.sh```

Latest dockserver 1.4.1 

after that, if I start the mount it starts normally ( v3.15-a0482dc2-ls1 ) 
the last version of the mount did not work for me so I take this version

this problem happened on 2 servers, 4 new lxc, on proxmnox 6.x and 7.x

at installation the script has detected the lxc and ask to write ''confirm''

**Comment by doob187** [comment]
Is the file exist on  /home ?

**Comment by dan3805** [comment]
yes it does 
![image](https://user-images.githubusercontent.com/35934387/151105011-f21bfb45-7b00-4488-92a1-6296c90f23ee.png)

**Comment by doob187** [comment]
Is the crontab added 

```sh
crontab  -e
```
And 
 This file exist 
```
/etc/cron.d/lxcstart
```

**Comment by dan3805** [comment]
sorry for the long delays

 the file exists, 
 
 but there is no crontab on all my lxcs (all of them are less than 1 month old)
 
 
![image](https://user-images.githubusercontent.com/35934387/151645122-02da9078-472f-4430-9d55-323f978b15ac.png)

![image](https://user-images.githubusercontent.com/35934387/151645145-8d6f0265-78d9-4f79-8883-fe93af6ac12e.png)

**Comment by doob187** [comment]
running follow command 

```sh
    $(command -v ansible-playbook) /opt/dockserver/preinstall/installer/subinstall/lxc.yml
```

**Comment by dan3805** [comment]
```  $(command -v ansible-playbook) /opt/dockserver/preinstall/installer/subinstall/lxc.yml
Error reading config file (/etc/ansible/ansible.cfg): File contains no section headers.
file: '<string>', line: 12
'inventory      = /etc/ansible/inventories/local\n' ```

**Comment by doob187** [comment]
run this command and again the ansible playbook  command 

```sh
cat > /etc/ansible/inventories/local << EOF; $(echo)
[local]
127.0.0.1 ansible_connection=local
EOF


```

**Comment by dan3805** [comment]
![image](https://user-images.githubusercontent.com/35934387/151717418-9d1ccce1-0bd0-421a-88ea-5e4961e2596e.png)

 there is no \n in the files
 
 
![image](https://user-images.githubusercontent.com/35934387/151717500-890798b6-2f73-4baf-8328-72c229acbf49.png)

**Comment by dan3805** [comment]
I have a friend who has the same ansible problem but on his backup restore of qbittorrent , bare metal VM , no lxc 
```
Restore is running for qbittorrent
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
31.5MiB 0:00:00 [ 320MiB/s] [ <=>                                                                                      ]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Please Wait, We are installing qbittorrent for you
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error reading config file (/etc/ansible/ansible.cfg): File contains no section headers.
file: '<string>', line: 12
'inventory      = /etc/ansible/inventories/local\n'
```

**Comment by doob187** [comment]
```sh

      cat > /etc/ansible/inventories/local << EOF; $(echo)
## CUSTOM local inventories
[local]
127.0.0.1 ansible_connection=local
EOF
      if [[ -f /etc/ansible/ansible.cfg ]]; then
        $(command -v mv) /etc/ansible/ansible.cfg /etc/ansible/ansible.cfg.bak
      fi
cat > /etc/ansible/ansible.cfg << EOF; $(echo)
## CUSTOM Ansible.cfg
[defaults]
deprecation_warnings = False
command_warnings = False
force_color = True
inventory = /etc/ansible/inventories/loca
retry_files_enabled = False
EOF

```
This should fix them

**Comment by dan3805** [comment]
![image](https://user-images.githubusercontent.com/35934387/151889090-4c28bdc5-dd1c-476b-8d6f-d59e90e6d458.png)

Yes ! it seems to have worked! everything is fine after a reboot 

 but i had to do the command as root :)
