### ISSUE TITLE
Docker: Compose check of jellyfin has failed

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#363]
![image](https://user-images.githubusercontent.com/35934387/151718247-886345ac-e7b6-45ad-901f-fe0a53491a10.png)

```
docker-compose logs | grep error
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 5, column 5
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 34, column 6 
```

I don't really understand the errors that relate to jellyfin docker name and traefik label... 🤷‍♂️😂

**Comment by drag0n141** [comment]
Check again, for me the Compose is now working.
