### ISSUE TITLE
ENV does not fill on deployment.

### ISSUE THREAD

**Issue by justinglock40** [dockserver/dockserver#368]
https://github.com/dockserver/dockserver/blob/930816e42796a741c29b59ec2d14936a2d834c94/apps/mediaserver/jellyfin.yml#L14

This line only creates a blank env var line. for URL

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/b58d870ba4077236ba1e91f0a1eb4b1424742f5d#diff-573ad243f4faab6934a63c1726fbde961f1b419a45742a742510def5639c662c

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/e2bff87339bd81907cbbb8a4f0390166c518780c
