### ISSUE TITLE
Backup script and /mnt/move ( migration )

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#484]
the rsync command in the backup docker is trying to rename the files in the wrong location 

( `/mnt/downloads/` folder instead of `/mnt/move` folder )

![image](https://user-images.githubusercontent.com/35934387/173167884-9b69be49-a3c2-4b41-8837-a94bfcb6be71.png)

**Comment by dan3805** [comment]
picture from dave- in the discord

**Comment by TheCableGuy99** [comment]
Im here as well :)

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/7bd4aa5f9888b4601bada3ff1fd5f9e22703d6d3

**Comment by doob187** [comment]
Its not wrong 
It's the dammed rsync in the uploader from pg or the shit file read and map command from phzysk

It's picks too fast the files 

I have added a lot of code now

**Comment by TheCableGuy99** [comment]
Cheers, i’ll try it later and let you know how it worked out :)

**Comment by TheCableGuy99** [comment]
Hey,

So I've stopped ALL containers and run it again, now I get this error:

`root@plexguide ~ # sudo wget -qO- https://raw.githubusercontent.com/dockserver/dockserver/master/backup.sh | sudo bash
Error response from daemon: No such container: uploader
bash: line 32: syntax error near unexpected token `fi'
bash: line 32: `fi'`

Any ideas?

**Comment by doob187** [comment]
https://github.com/dockserver/dockserver/commit/053d290b17fabe46912108b13f1673af46fd8828
