### ISSUE TITLE
FR - Upload also to Dropbox Enterprise possible  [NOT YET PLANED|doob]

### ISSUE THREAD

**Issue by ShadowFM** [dockserver/dockserver#502]
**Is your feature request related to a problem? Please describe.**
Currently there is only one provider to which files could be uploaded (Google)

**Describe the solution you'd like**
Make the entire stack compatible with Dropbox Enterprise

**Describe alternatives you've considered**
Unfortunately, currently no alternative idea besides Dropbox, which includes the limitations of the former Drive model (Since there is no more Unlimited at Google).

**Additional context**
As I was able to find out, Dropbox Enterprise includes only one restriction: the upload per file cannot exceed 2TB.
There are no other limits, you can upload/download as much as you want per day and there is no storage limit either.
I therefore consider Dropbox Enterprise to be a very good alternative to Google.

**Comment by doob187** [comment]
Is there any way to bypass the upload limit??

What limits they have??

Or how it works ?
I never used Dropbox,
so Idk  what I need to add or to change 


And I don't what to buy or create a account and see how it works 

We.know Google is unlimited  
So we don't switch to another one 

TeamDrives  just have one limited  400k files

That's all 

So why we need to add dropbox ??
And how many people use them ??

We you post some samples how it works .. maybe I could think about them  ... but for now we used just  Google drives

**Comment by ShadowFM** [comment]
You may not believe it, but there are no limits, except that the size of a file must not exceed 100GB.
There is an API that is limited to 20.000.000 accesses per day, but this is not used for rclone.

An upload limit as with Google (750GB/day) does not exist with the Dropbox subscription, you can really upload as much as you want, currently I also move my library from Google to Dropbox and migrate per day about 7TB, and not with detours of service accounts or similar but just pure uploading.
Initially, the Dropbox cloud has a size of 3TB, but this is automatically increased as soon as a used storage of 80% is reached, if necessary, you can also contact support and have the storage expanded. I have contacted the support and initially expanded by 200TB, this went without problems.

Dropbox is integrated into rclone like Google, should the desire exist also as Encrypted variant what works great.

Should you otherwise continue to use rclone then I would make the adjustments in the rclone config, that would not be an issue for me if another provider is to be integrated.

**Comment by doob187** [comment]
```
rclone listremotes | grep "$1"
```

Van you give me a sample of the configuration or rclone 

To see what I need to add or change 

So I could add them for the next release..

[[ when I have the time ]]

**Comment by ShadowFM** [comment]
Don't wonder, I'm coming from plexguide which I want to migrate..

```
rclone --config=/opt/appdata/plexguide/rclone.conf listremotes | grep "$1"

dropbox:
dropcrypt:



[dropbox]
type = dropbox
token = {"access_token":"","token_type":"bearer","refresh_token":"","expiry":"2022-07-16T02:36:55.861798946+02:00"}
client_id =
client_secret = 

[dropcrypt]
type = crypt
remote = dropbox:/<Name_of_dropbox_advanced_account>/encrypt
filename_encryption = standard
directory_name_encryption = true
password =
password2 =
```

**Comment by doob187** [comment]
Ah okay 
I see this should not be hard to add 

Let me think about. 🤔

**Comment by doob187** [comment]
Are there any special commands for uploading files to Dropbox  ??

**Comment by doob187** [comment]
I think the beat option is to use a different docker 

So we don't have any conflicts

For uploading we could also made a separation in dockers

Mount and uploader for Dropbox could be in one image 

I have read on Dropbox the same api is used for upload

So we can mount and uploading in one step

**Comment by ShadowFM** [comment]
Hey doob, sorry was in vacation.
No not really, it works like the encryption path in Google so anything which would be uploaded over the dropcrypt folder will be encrypted.
In my eyes it's pretty "standard"

**Comment by doob187** [comment]
What command for uploading did you use at the moment ?

It's hard to find a good command for me .. when I don't use it ..

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by ShadowFM** [comment]
What I'm using to mount is the following:

`/usr/bin/rclone mount dropcrypt: /mnt/dropcrypt --config=/opt/appdata/plexguide/rclone.conf --log-level=NOTICE --uid=1000 --gid=1000 --umask=002 --allow-other --timeout=1h --tpslimit=0 --user-agent=je6EFl1OKecj8 --dir-cache-time=5m --vfs-cache-mode=writes --vfs-cache-max-age=15m --vfs-cache-max-size=350G --vfs-read-chunk-size-limit=1024M --vfs-read-chunk-size=64M --buffer-size=16M`

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by fscorrupt** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.

**Comment by drag0n141** [comment]
@ShadowFM It should work now with Dropbox :) Can you test the Mount with your rclone.conf?
