### ISSUE TITLE
SA mount -- " error opening service account credentials file: open /system/mount/keys/.json "

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#506]
for a few days the SA mount seems to be looking for the .json file instead of 1.json on the first start,

if I copy my 1.json key to .json the SA mount works!

```[Mount] **** update system packages ****
[Mount] **** install build packages from requirements ****
/system/mount/drive.csv exist
2022/07/17 19:21:37 Failed to create file system for "tdrive1:": drive: failed when making oauth client: error opening service account credentials file: open /system/mount/keys/.json: no such file or directory
2022/07/17 19:21:38 Failed to create file system for "tdrive2:": drive: failed when making oauth client: error opening service account credentials file: open /system/mount/keys/.json: no such file or directory
--------------------
[remote]
type = union
upstreams = gcrypt: gdrive: 
action_policy = all
create_policy = all
search_policy = all
cache_time = 120
--------------------
------------------------------
```

if i copy the keys like that 
`sudo cp /opt/appdata/system/mount/keys/1.json /opt/appdata/system/mount/keys/.json`

then I restart the mount 
`sudo docker stop mount`
`sudo fusermount -uzq /mnt/remotes && sudo fusermount -uzq /mnt/unionfs`
`sudo docker restart mount`

```----------------------------------------------------
[Mount] **** update system packages ****
[Mount] **** install build packages from requirements ****
/system/mount/drive.csv exist
          -1 xxxx-xx-xx 00:00:00        -1 .anchors
          -1 xxxx-xx-xx 00:00:00        -1 appbackups
          -1 xxxx-xx-xx 00:00:00        -1 encrypt
          -1 xxxx-xx-xx 00:00:00        -1 encrypt
--------------------
[remote]
type = union
upstreams = gcrypt: gdrive: tcrypt-tdrive1: tcrypt-tdrive2: tdrive1: tdrive2: 
action_policy = all
create_policy = all
search_policy = all
cache_time = 120
--------------------
------------------------------
```
### after that , if i restart again the mount I see those lines 

```
[tdrive1]
type = drive
scope = drive
server_side_across_configs = true
service_account_file = /system/mount/keys/1.json
service_account_file_path = /system/mount/keys
team_drive =XXXXXXXXXXXXXXXXX

[tdrive1]
type = drive
scope = drive
server_side_across_configs = true
service_account_file = /system/mount/keys/1.json
service_account_file_path = /system/mount/keys
team_drive = XXXXXXXXXXXXXXXXX

[tdrive2]
type = drive
scope = drive
server_side_across_configs = true
service_account_file = /system/mount/keys/1.json
service_account_file_path = /system/mount/keys
team_drive = XXXXXXXXXXXXXXXXX

[tdrive2]
type = drive
scope = drive
server_side_across_configs = true
service_account_file = /system/mount/keys/1.json
service_account_file_path = /system/mount/keys
team_drive = XXXXXXXXXXXXXXXXX
``` 

comment edit : yes it was taking the keys 3 ,( old mount folder ) but it does the same on fresh install :)

**Comment by dan3805** [comment]
3rd server did not happend ... not sure why !

**Comment by doob187** [comment]
Let me look middle of the week 
Then I can change it when it's not working

**Comment by doob187** [comment]
Should be fixed

**Comment by doob187** [comment]
In the next major update from mount and uploader 

We made a bunch of rework of the code 

ServiceKey will be rotated much easier as before ( live remapping without restarting the mount ) 

Push vfs clean and forget from uploader to the mount docker

Mount runs as rclone rc command 

Mount : rclone webui will be showing

**Comment by doob187** [comment]
https://user-images.githubusercontent.com/60312740/183239153-4477af72-9df9-442c-b7c6-83a89b2c1e34.mp4

![unknown](https://user-images.githubusercontent.com/60312740/183239272-975b8858-93a0-42ee-93bc-69a7bbc5275d.png)

**Comment by dan3805** [comment]
nice ! 
I can't wait to try this .

for the moment I have not reproduced the problem because I made a backup of the entire `/opt/appdata/system` folder for the migration.

`sudo tar --warning=no-file-changed --ignore-failed-read --absolute-names --warning=no-file-removed --use-compress-program=pigz -C /opt/appdata/system -pcf /home/<my_username>/system.tar.gz ./`

that way I avoid mistakes and typo error.

but I will soon create different configs for all my vms

we can close this for now
