### ISSUE TITLE
Fresh Install on Oracle OCI,  Startup Loop Error.

### ISSUE THREAD

**Issue by Batminer** [dockserver/dockserver#509]
**Describe the bug**
I can't get the dockserver suite to install. 

**To Reproduce**
Follow the instructions from this githup page.
Easy Mode install

> Run the following command:
sudo wget -qO- https://git.io/J3GDc | sudo bash

> Long commmand if the short one doesn't work.
sudo wget -qO- https://raw.githubusercontent.com/dockserver/dockserver/master/wgetfile.sh | sudo bash

[INSTALL] DockServer **** install build packages ****
[INSTALL] DockServer **** remove old links  ****
docker.dockserver.io/dockserver/docker-dockserver:latest
docker: Error response from daemon: Conflict. The container name "/dockserver" is already in use by container "834d01f34e93848a3680d9cfcf20e0739fd151960693bce63e35595b6b66b456". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Expected behavior**
I expected this to continue with the installation.

**Desktop (please complete the following information):**
Oracle Always Free Tier
Shape: ARM64 VM.Standard.A1.Flex
OCPU count:  4
Network bandwidth (Gbps):  4
Memory (GB):  24
Local disk:  Block storage only
Partner Provided OS: Ubuntu Desktop 20.04 (RDP)
Region: Netherlands Northwest (Amsterdam)

**Additional context**
I was able to install dockserver locally on a Raspberry Pi 4 8GB in my home lab and loved the way it worked. This why I proceeded to create an instance on the Oracle Free Cloud VPS.
Thank you all for your hard work and support.

**Comment by doob187** [comment]
I will check this what could it be

**Comment by doob187** [comment]
I have some days it tested 

And ORACLE cloud is a nightmare to get Traefik working

I can't get on oracle cloud (,free tier ,) a working traefik install 

Over script
Over commands 
Each as single command 
Nothing worked
