### ISSUE TITLE
Latest uploader stops uploading queue after some time.

### ISSUE THREAD

**Issue by cyb3rgh05t** [dockserver/dockserver#512]
``ghcr.io/dockserver/docker-uploader:latest``

For some reason the uploader stops uploading files after some, even if there is a huge queue waiting to be uploaded.

I tried reinstalling the whole system folder with mount and uploader but still the same issue. logs doesnt show any errors.
i also tried to downgrade the uploader to the oldest version possible in docker-uploader packages without any success.

i need to restart uploader to get it uploading some files but after some time it stops again.

is there something other i can check to resolve this?

thanks

**Comment by cyb3rgh05t** [comment]
also i realised that uploader doesnt add new downloaded stuff to the check.log file until i restart the container

**Comment by fscorrupt** [comment]
if you have a big history you could try to purge uploader history (delete the json files in those folders) `/opt/appdata/system/uploader/json/upload`
and `/opt/appdata/system/uploader/json/done` im also at the latest tag, without issues.

**Comment by cyb3rgh05t** [comment]
its a fresh installation of the whole system folder, maybe 20 uploaded files. it uploads 2 files and then stops uploading. need to restart to get it uploading again

**Comment by fscorrupt** [comment]
hm... whats the latest version that works for you?

**Comment by cyb3rgh05t** [comment]
i managed now to get it working by restarting the whole server. i think that fixed it. thanks
