### ISSUE TITLE
[SOLVED | FILLED TDRIVE] : Uploader is cycling uploads from sonarr and sonarr4k

### ISSUE THREAD

**Issue by TheCableGuy99** [dockserver/dockserver#514]
Every few days my hard drive fills up and I have to delete downloaded content from the server.

Upon investigation it appears anything in the following folders are not being deleted and is just being re-uploaded all the time:
/mnt/downloads/Plex/TV/TV
/mnt/downloads/Plex/TV/TV-4K

It has to be said that Radarr and Radarr4k are working fine, it's just the TV series. Sometimes I see the file get to 100% uploaded and it immediately starts to upload it again. At first I thought this was because it might not have finished unpacking yet but this isn't the case I've since found out.

In the "Completed" section of uploader I can see it's showing the series that have been uploaded but as said it's still uploading the same file over and over again. The more downloads completed, the bigger the queue/cycle of things that are being constantly uploaded.

I checked with Sonarr and Radarr support channels and they said it's not their issue. Someone in the DockServer general chat said it's the uploader that's supposed to delete them.

I also asked in the official support channel but am not getting any reply so thought I'd try on here.

Thanks for any help.

**Comment by TheCableGuy99** [comment]
For anyone coming across this in the future I found the issue: Logs of uploader show:
Failed to copy: googleapi: Error 403: The file limit for this shared drive has been exceeded

Looks like I need to move things over.

**Comment by doob187** [comment]
Okay I will add a part to show then on the UI ..

Give me some days 

Or use the multiuploader option

**Comment by doob187** [comment]
REOPEN FOR ADD !

**Comment by doob187** [comment]
So as possible fix to upload zo other drives 

First way * ( take some times and need some changes ) *


1. Stop uploader mount sonarr radarr plex ( failsafe before files get removed )
2. Chmage the team_drive id  in  ```/opt/appdata/system/servicekeys/rclonegdsa.conf```
3. Add all keys from the old drive to the new team_drive
4. Add the new tdrive under ```/opt/appdata/system/rclone/rclone.conf```
5. Run ```fusermount -uzq /mnt/remotes && fusermount -uzq /mnt/unionfs```
6. Start the stopped containers from mount then uploader and after this once plex radarr and and and ( all stopped containers)


Second way more difficult

1. Add all keys to a Google Group
2. Add the Google Group to the teamdrives ( old and new once )
3. Add the team_drive / replace the id on the rclonegdsa.conf (( uploader docker ))
4. Add the new tdrive under ```/opt/appdata/system/rclone/rclone.conf``` (( Mount docker ))
6. Run ```fusermount -uzq /mnt/remotes && fusermount -uzq /mnt/unionfs```
7. Start the stopped containers from mount then uploader and after this once plex radarr and and and ( all stopped containers)


Master way:

1. Add all keys to the Google Group
2. Add how many drives you want to the mount container
3. Use the crypted or unencrypted csv file ( don't add the filed drive in the csv file for the uploader !! )
4. Stop and start the necessary dockers 

Plex mount sonarr radarr and so go on ..

Now you can upload to so many drives you want

**Comment by TheCableGuy99** [comment]
Thank you doob, I appreciate all that 👍
