### ISSUE TITLE
plex Restore , Error: No such container: plex

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#517]
I have often restored plex with the dockserver menu without the docker actually being created
```
sudo docker logs -f plex
Error: No such container: plex
```
in this time to fix this I made this command to deploy plex.

`sudo cp /opt/dockserver/apps/mediaserver/plex.yml /opt/appdata/compose/docker-compose.yml && sudo docker compose -f /opt/appdata/compose/docker-compose.yml up -d`

and plex work 

I never really found the cause.

it happened to me on several configurations like lxc / VM and on servers without virtualization

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by fscorrupt** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.
