### ISSUE TITLE
Separate uploads transfers and queue setting

### ISSUE THREAD

**Issue by TheCableGuy99** [dockserver/dockserver#521]
**Is your feature request related to a problem? Please describe.**
As I understand it whatever you set the the "TRANSFERS=" setting to in the .env file is the number of uploads it will perform at once. But I also understand this setting to have a dual setting in that it also affects the number of uploads it has to wait to be ready before it starts uploading. This is really frustrating because if I have a single file waiting to be uploaded you have to wait until has to wait for 4 different things to be ready to be uploaded (If I want it to have the ability to upload 4 things at once). As a result I have to set the "TRANSFERS" to "1" so it will upload as soon as a file is ready to be uploaded. However, this restricts the upload capacity to 1 file at once which is far less than the able capacity.

**Describe the solution you'd like**
Can we please separate these settings so TRANSFERS can mean solely the maximum number of uploads at once, and add a new setting for "QUEUE" meaning when this number is reached it will start uploading. I.E., "TRANSFERS=4" and "QUEUE=1" would mean it can upload 4 files at once but doesn't have to wait for 4 files to be ready and can start uploading with just 1 item waiting.

**Describe alternatives you've considered**
I can only set it to TRANSFERS=1 to allow things to be uploaded when a single item is ready but as said this restricts the number of simultaneous uploads. I have no control over alternatives.

**Additional context**
I think I've covered it well but if not please let me know if you need any clarification and thank you for your consideration.

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by fscorrupt** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.

**Comment by fscorrupt** [comment]
Planned in Next release!
