### ISSUE TITLE
Authelia bypass not working when using middleware chain-no-auth

### ISSUE THREAD

**Issue by dan3805** [dockserver/dockserver#532]
I noticed with some application that I modified or added to dockserver that the bypass did not work

I thought it was enough to add  `chain-no-auth@file`  instead of `chain-authelia@file`

like that for exemple : 
      - "traefik.http.routers.crewlink-rtr.middlewares=chain-no-auth@file"
      

but it doesn't work , it looks like the traefik configuration is always prioritized

/opt/dockserver/traefik/templates/compose/docker-compose.yml
     ` 
     - --entrypoints.https.http.middlewares=chain-authelia@file
     `
    
   **in my tests, I removed this line from the traefik configuration and I redeployed and here is the result**
     
   with the entrypoint :
<img width="405" alt="Capture d’écran, le 2022-09-11 à 16 36 35" src="https://user-images.githubusercontent.com/35934387/189547903-89a83c5d-1f9a-45fe-99c2-5d32ea453103.png">
without the entrypoint :
<img width="327" alt="Capture d’écran, le 2022-09-11 à 16 38 58" src="https://user-images.githubusercontent.com/35934387/189547987-c91d8f43-8bcc-40ad-8e27-9d9d22c37d7c.png">

unfortunately I do not have access to the  file ubuntu.sh from the dockserver docker install ( `/opt/dockserver/apps/.installer/ubuntu.sh` so I cannot add an application to the list 

  ```  
    if [[ ${typed} == "xteve" || ${typed} == "heimdall" || ${typed} == "librespeed" || ${typed} == "tautulli" || ${typed} == "nextcloud" ]]>
     { head -n 55 $conf;
     echo "\
    - domain: ${typed}.${DOMAIN}
      policy: bypass"; tail -n +56 $conf; } > $confnew
 ```

### I was just wondering, with v2 on the road .

wouldn't it be better to bypass authelia with a middleware chain and no longer use the authelia bypass or are we going to make more advanced authelia configurations for each application?

**Comment by fscorrupt** [comment]
This issue is was closed immediately , one dev was informed

**Comment by fscorrupt** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.
