### ISSUE TITLE
Jellyfin not starting

### ISSUE THREAD

**Issue by tiberio87** [dockserver/dockserver#608]
I have a dedicated on hetzner, taefik and authelia working perfect but jellyfin dont start.
`
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/40-gid-video
cont-init: info: /etc/cont-init.d/40-gid-video exited 0
cont-init: info: running /etc/cont-init.d/98-nvidia-patch
cont-init: info: /etc/cont-init.d/98-nvidia-patch exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mod-themepark: starting
-----------------------------
|  Jellyfin theme.park Mod  |
-----------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_THEME'=organizr

No domain set, defaulting to theme-park.dev
No scheme set, defaulting to https
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mod-themepark successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun jellyfin (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
wait mount /mnt/unionfs
wait mount /mnt/unionfs
`

the container gets stuck on mount of unionfs.

**Comment by drag0n141** [comment]
Is your Mount Container running?
